# stats280

## Welcome

I'm going to start this twitter stats course now #stats280. I'll be 
aiming it at UG bios with a little background knowledge. I won't do
a dedicated probability section but will try to explain everything as I go.
  
However, it's a stats course, not an R course. I'll assume tidyverse 
and modelr are loaded, but otherwise include pkg info. I like this R
course as a starter. #stats280 http://dzchilds.github.io/aps-data-analysis-L1/ 

I'm using a github repo. But once I get going I will storify the tweets 
and interesting replies. Feel free to PR or open issues on github. #stats280
https://github.com/timcdlucas/stats280

Some principles: I'll focus on general understanding, not learning a 
long list of specific tests. Focus on the similarities between methods,
not the differences. Using sims to explore, understand and check things 
is great. #dataviz is vital. #stats280

And as a final aside, I am agnostic between frequentism, bayes and 
more machine learning type approaches. #stats280



## Introduction

### Tasks

The three broad tasks in statistics are exploration, prediction and 
confirmation/hypothesis testing. I'll come back to this a lot. #stats280
https://dynamicecology.wordpress.com/2013/10/16/in-praise-of-exploratory-statistics/


They ask different questions. Which of these hypotheses does my data 
support? How/how well can I predict something of interest? What is 
interesting in my data? #stats280

### Explore

```{taskscode}

# Explore visually
mtcars %>%
  gather("var", "value", -mpg) %>% 
  ggplot(aes(x = value, y = mpg)) +
    geom_point() +
    geom_smooth() + 
    facet_wrap(~ var, scales = "free") 
#stats280

ggsave('figs/mtcars_explore.png')

# Explore with correlation
mtcars %>%
  gather("var", "value", -mpg) %>% 
  group_by(var) %>% 
  summarise(p = cor(value, mpg, method = 'pear')) %>% 
  arrange(abs(p))
#stats280
  
### confirmatory 

# Do formal frequentist test on 1 variable
lm(mpg ~ wt, mtcars) %>% anova

### predictive
  
  # Fit two predictive models
  lm <- lm(mpg ~ ., mtcars)
  mean(lm$residuals ^ 2)
  
  sv <- e1071::svm(mpg ~ ., mtcars)
  mean(sv$residuals ^ 2)
  plot(sv$fitted ~ mtcars$mpg)


```

svm_obs_fit.png







### An analysis

It's useful to split "an analysis" into parts to highlight similarities. 
One way: Model selection, model structure, parameter estimation and 
implementation. #stats280 

- analysis_schem.png

Model selection: when we have multiple models or hypotheses how do we
choose which one(s) to keep or are good? Our answer could be 1 or more 
"best" models or "we don't know". Examples: Frequentist tests, AIC, 
predictive accuracy, Bayes factors. #stats280

Model structure: what is the structure of the underlying mathematical 
model? There is always an underlying model, though it might be
hard to see. Examples: linear model (maybe discrete x's), decision trees, 
random effects. #stats280

Parameter estimation: a model has parameters. How (in theory) do we 
decide what they are? Examples: maximum likelihood, bayesian estimation.
#stats280

-par-choice-fig.png

ggplot(mtcars, aes(disp, mpg)) + 
  geom_point() +
  geom_abline(intercept = 32, slope = -0.05) + 
  geom_abline(intercept = 33, slope = -0.06, colour = 2) + 
  geom_abline(intercept = 34, slope = -0.07, colour = 3) + 
  geom_abline(intercept = 32.5, slope = -0.07, colour = 4) + 
  geom_abline(intercept = 35, slope = -0.08, colour = 5) + 
  geom_abline(intercept = 29, slope = -0.05, colour = 6) 



Implementation: how do we literally do what we decided above? If we 
want to select pars by MaxLikelihood, how do we do that? Becomes more
important e.g. in Bayes when we have to use an approximation. Do we use
INLA or MCMC etc. #stats280



This schematic covers more analyses than one might think. To demonstrate, I'll fit 
2 models, (y = bx + c and y = c) and select between them in 3 ways (ignoring 
implementation for now). #stats280
- analysis_schem.png


1) Select pars that minimise absolute error between data and model. 
Choose model that best predicts holdout data. 2) Pars that maximise 
likelihood, chose model with frequentist test 3) Select pars and model
with Bayes. #stats280
 
                                                                               

```{setup}
library(tidyverse)
library(modelr)
```


```{pipeline_setu}p
# One model

## Model selection performed differently
## Parameter selection performed differently.

## Compare y ~ X1 + 1, y ~ 1


ggplot(mtcars, aes(disp, mpg)) + geom_point()
```

1) MaxLike and frequentist test
```{pipeline1}
## Fit by absolute error
## Compare by crossvalidation.

library(quantreg)
crossv_mc(mtcars, 10) %>% 
  mutate(m1 = map(.$train, ~rq(mpg ~ disp, dat=.)),
         m2 = map(.$train, ~rq(mpg ~ 1, dat=.))) %>% 
  summarise(e1 = mean(map2_dbl(m1, .$test, mae)), 
            e2 = mean(map2_dbl(m2, .$test, mae)))
```
abs_lm_fig.tex


2)
```{pipeline2}
## Fit by maximum likelihood
## Compare with frequentist aov

f1 = lm(mpg ~ disp + 1, mtcars)
f2 = lm(mpg ~ 1, mtcars)

anova(f1, f2)
```

maxlike_lm_fig.tex



3) Bayes and Bayes factor
```{pipeline3}

## Fit by bayes
## Compare by bayes factor
library(INLA)
b1 = inla(mpg ~ disp + 1, data =  mtcars, control.compute=list(waic=TRUE))
b2 = inla(mpg ~ 1, data = mtcars, control.compute=list(waic=TRUE))
b1$mlik[1] - b2$mlik[1]
```



This way of dividing an analysis will form the backbone of the course
content. We'll look at model selection (frequentist, bayes, CV, etc.), 
then parameter estimation, then lots of models and finally implementation.
#stats280

- analysis_schem.png






```{plots}

library('RColorBrewer')
library('tikzDevice')

#plot(1:10,1:10, col='white')
#text(runif(1,0,10),runif(1,0,10),expression(paste(frac(1,paste(sigma, sqrt(paste(2, pi)))),~e^-~frac((x~-~mu)^2,paste(2, sigma^2)))), cex=1.3)
r <- brewer.pal( 8, 'Set1')[1]
b <- brewer.pal( 8, 'Set1')[2]
g <- brewer.pal( 8, 'Set1')[3]
p <- brewer.pal( 8, 'Set1')[4]
o <- brewer.pal( 8, 'Set1')[5]

br <- brewer.pal( 8, 'Set1')[7]
arrowWidth <- 8


tikz("~/Dropbox/Documents/stats280/figs/maxlike_lm_fig.tex", width = 6, height = 6, 
standAlone = TRUE,
packages = c("\\usepackage{tikz}",
"\\usepackage[active,tightpage,psfixbb]{preview}",
"\\PreviewEnvironment{pgfpicture}",
"\\setlength\\PreviewBorder{0pt}",
"\\usepackage{amssymb}",
"\\usepackage[scaled]{helvet}",
"\\renewcommand*\\familydefault{\\sfdefault}", 
"\\usepackage[T1]{fontenc}",
"\\usepackage{textgreek}"))


par(mar=c(4,4,0,0)+0.3, cex=1.8)

plot( 1:5, 1:5, col='white', xlab = '$x$', ylab='$y$', xlim=c(0,5), ylim=c(0,5),xaxs='i', yaxs='i' )

abline(2, 0.3, col=p, lwd=7)



x2 <- 2.5
y2 <- seq(1.95, 3.55, length.out=100)
e2 <- dnorm(y2, 0.3*x2+2,  0.2)/3
xe2 <- x2 + e2

lines(y2~rep(x2, 100), col=r, lty=5)
lines(y2~xe2, lwd = 5, col=r)

yData <- 2.5

points(x2, yData, col=b, pch=16, cex=1)
arrows(x2, 0.3*x2+2, x2, yData+0.04, col=b, lwd=3, length=0.1)
arrows(x2, yData, x2+dnorm(yData, 0.3*x2+2, 0.2)/3 , col=b, lwd=3, length=0.1)

text(x2-0.4, yData-0.2, '${\\color[HTML]{377EB8}(x,y)}$')


text(2.6, 1.1, '$ \\mathcal{L}({\\color[HTML]{984EA3}\\beta})=\\textrm{dnorm}({\\color[HTML]{377EB8}y} - {\\color[HTML]{377EB8}x}{\\color[HTML]{984EA3}\\beta})$', cex=1.5)

dev.off()






tikz("~/Dropbox/Documents/stats280/figs/abs_lm_fig.tex", width = 6, height = 6, 
standAlone = TRUE,
packages = c("\\usepackage{tikz}",
"\\usepackage[active,tightpage,psfixbb]{preview}",
"\\PreviewEnvironment{pgfpicture}",
"\\setlength\\PreviewBorder{0pt}",
"\\usepackage{amssymb}",
"\\usepackage[scaled]{helvet}",
"\\renewcommand*\\familydefault{\\sfdefault}", 
"\\usepackage[T1]{fontenc}",
"\\usepackage{textgreek}"))


par(mar=c(4,4,0,0)+0.3, cex=1.8)

plot( 1:5, 1:5, col='white', xlab = '$x$', ylab='$y$', xlim=c(0,5), ylim=c(0,5),xaxs='i', yaxs='i' )

abline(2, 0.3, col=p, lwd=7)



x2 <- 2.5

yData <- 2

points(x2, yData, col=b, pch=16, cex=1)
arrows(x2, 0.3*x2+2, x2, yData+0.04, col=b, lwd=3, length=0.1)
#arrows(x2, yData, x2+dnorm(yData, 0.3*x2+2, 0.2)/3 , col=b, lwd=3, length=0.1)

text(x2-0.4, yData-0.2, '${\\color[HTML]{377EB8}(x,y)}$')


text(2.6, 1.1, '$ \\textrm{Abs error}=\\textrm{abs}({\\color[HTML]{377EB8}y} - {\\color[HTML]{377EB8}x}{\\color[HTML]{984EA3}\\beta})$', cex=1.5)

dev.off()



```